Shift+UP seek 600
Shift+DOWN seek 600
Alt+RIGHT add video-rotate 90
Alt+LEFT add video-rotate -90
Alt+- add video-zoom -0.25
Alt++ add video-zoom 0.25
Alt+= set video-zoom 0
] add speed 0.1
[ add speed -0.1
p cycle pause


