# -*- conf -*-

# For documentation on these options, see `man fnott.ini`
background=141216ff
# Global values
# output=<undefined>#
min-width=300
max-width=500
max-height=300
# stacking-order=bottom-up
# anchor=top-right
# edge-margin-vertical=10
# edge-margin-horizontal=10
notification-margin=8
# icon-theme=hicolor
# max-icon-size=32
selection-helper=fuzzel
# selection-helper-uses-null-separator=no
# play-sound=aplay ${filename}

# Default values, may be overridden in 'urgency' specific sections
# layer=top
# background=3f5f3fff

border-color=00b7ebff
# border-radius=0
border-size=1

# padding-vertical=20
# padding-horizontal=20

# dpi-aware=no

title-font=dejavu
# title-color=ffffffff
# title-format=<i>%a%A</i>

summary-font=dejavu
# summary-color=ffffffff
# summary-format=<b>%s</b>\n

body-font=dejavu
# body-color=ffffffff
# body-format=%b

progress-bar-height=20
# progress-color=ffffffff
# progress-style=bar

# sound-file=
# icon=

# Timeout values are in seconds. 0 to disable
max-timeout=5
# default-timeout=0
# idle-timeout=0

[low]
background=141216ff
max-timeout=5
# title-color=888888ff
# summary-color=888888ff
# body-color=888888ff

[normal]
background=141216ff
max-timeout=7

[critical]
background=141216ff
max-timeout=10
